version: "3.8"
services: 
    backend:
        build: ./api
        container_name: "calendar-api"
        ports: 
            - "8080:8080"
        depends_on: 
            - db
        networks: 
            - webappnetwork

    frontend:
        build: ./client
        tty: true
        container_name: "calendar-front"
        ports: 
            - "3000:3000"
        networks: 
            - webappnetwork
            
    db:
        image: mongo:latest
        container_name: "calendar-db"
        volumes: 
            - ./data/db:/data/db
        ports: 
            - 27017:27017
        networks: 
            - webappnetwork

    networks: 
        webappnetwork:
            driver: bridge