import styles from "./CharacterSheet/Stats/stats.module.scss";

export const hpColors: any = {
  "-5": styles.veyLowStat,
  "-4": styles.veyLowStat,
  "-3": styles.negativeStat,
  "-2": styles.negativeStat,
  "-1": styles.negativeStat,
  0: styles.neutralStat,
  1: styles.positiveStat,
  2: styles.positiveStat,
  3: styles.positiveStat,
  4: styles.veryHighStat,
  5: styles.veryHighStat,
  6: styles.veryHighStat,
  7: styles.veryHighStat,
  8: styles.veryHighStat,
  9: styles.veryHighStat,
  10: styles.veryHighStat,
  11: styles.veryHighStat,
  12: styles.veryHighStat,
  13: styles.veryHighStat,
  14: styles.veryHighStat,
  15: styles.veryHighStat,
}